//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wbc.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class woobcEntities : DbContext
    {
        public woobcEntities()
            : base("name=woobcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<wbc_company> wbc_company { get; set; }
        public DbSet<wbc_post> wbc_post { get; set; }
        public DbSet<wbc_user> wbc_user { get; set; }
        public DbSet<wbc_user_ext> wbc_user_ext { get; set; }
        public DbSet<wbc_user_photo> wbc_user_photo { get; set; }
    }
}
