//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wbc.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class wbc_user_ext
    {
        public long UserID { get; set; }
        public System.DateTime Birthday { get; set; }
        public decimal Height { get; set; }
        public string City { get; set; }
        public string Birthplace { get; set; }
        public string Occupation { get; set; }
        public string ParentsDesc { get; set; }
        public sbyte IsUniqueChild { get; set; }
        public string IncomeDesc { get; set; }
        public string Hobby { get; set; }
        public sbyte IsAcceptLongDistance { get; set; }
        public string MinRequirement { get; set; }
        public string SpecialRequirement { get; set; }
        public string Introduction { get; set; }
        public string ToPartner { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
    }
}
